# Generated by Django 4.2.6 on 2023-10-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delayreport",
            name="order",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delay_reports",
                to="shop.order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delayreport",
            name="trip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delay_reports",
                to="shop.trip",
            ),
        ),
    ]
